name: Metrics
on:
  schedule: [{ cron: "30 23 * * 7" }]
  push: { branches: ["master", "main"] }
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}

          user: ruiiiijiiiiang
          template: classic
          base: header, activity, community, repositories, metadata
          config_animations: yes
          config_timezone: America/Chicago
          optimize: no
          use_prebuilt_image: yes

          output_action: commit
          filename: github-metrics.svg

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 10
          plugin_lines: yes
